# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10
  
[[main]]
  name = "Projects"
  identifier = "proj-menu"
  weight = 30

[[main]]
  name = "Current Projects"
  parent = "proj-menu"
  url = "#projects"
  weight = 20

[[main]]
  name = "All Projects"
  parent = "proj-menu"
  url = "projects"
  weight = 30

[[main]]
  name = "Publications"
  identifier = "pub-menu"
  weight = 35
 
[[main]]
  name = "Recent Publications"
  parent = "pub-menu"
  url = "#publications"
  weight = 10
 
[[main]]
  name = "All Publications"
  parent = "pub-menu"
  url = "publication"
  weight = 20

[[main]]
  name = "Team"
  url = "#team"
  weight = 20
  
[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 40
  
[[main]]
  name = "Awards"
  url = "#awards"
  weight = 50

[[main]]
  name = "Service"
  url = "#service"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
